name: test-windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Rust
      uses: microsoft/setup-msbuild@v1
      uses: ilammy/setup-nasm@v1
      uses: seanmiddleditch/gha-setup-ninja@master
      run: |
        rustup default stable-x86_64-pc-windows-msvc
        rustc -vV
        cargo -vV
        nasm --version
        ninja --version
