name: test-windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Rust
        run: |
          rustup-init -yv --default-toolchain stable --default-host x86_64-pc-windows-msvc
          rustc -vV
          cargo -vV
