name: test-windows

on:
  [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    #- uses: ilammy/setup-nasm@v1
    #- uses: ashutoshvarma/setup-ninja@master
    #- name: Setup Visual Studio 2019
    #  run: |
    #    cmd.exe /c "call `"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat`" && set > %temp%\vcvars.txt"
    #    Get-Content "$env:temp\vcvars.txt" | Foreach-Object {
    #      if ($_ -match "^(.*?)=(.*)$") {
    #        $key=$matches[1].ToString()
    #        $value=$matches[2].ToString()
    #        echo "$key=$value"
    #        echo "$key=$value" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
    #      }
    #    }
    #    $env:path
    - name: SHA8
      run: |
        $sha8=$env:GITHUB_SHA.Substring(0, 8)
        echo "SHA8=$sha8" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8
    - name: Check
      run: |
        $env:path
        #ninja --version
        #nasm --version
        echo SHA=${{ github.sha }}
        echo SHA=$env:GITHUB_SHA
        echo REF=${{ github.ref }}
        echo REF=$env:GITHUB_REF
        echo SHA8=${{ env.SHA8 }}
        echo SHA8=$env:SHA8
